// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:cloud_firestore/cloud_firestore.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8lJ8hOd9BoD-ZR-IwTW6Byn4NoRu6cFQ',
    appId: '1:60440379548:web:963bad9492c5888ed62d59',
    messagingSenderId: '60440379548',
    projectId: 'bimaapp2025may',
    authDomain: 'bimaapp2025may.firebaseapp.com',
    storageBucket: 'bimaapp2025may.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4Zia88lDSVPiggQCl1jdf7cZAYoKWEc',
    appId: '1:60440379548:android:80d1ec07ef1e3ea5d62d59',
    messagingSenderId: '60440379548',
    projectId: 'bimaapp2025may',
    storageBucket: 'bimaapp2025may.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQk65-1cZp3SMOd1u0-OL6zFlfluUTnAY',
    appId: '1:60440379548:ios:177372424f6d77f4d62d59',
    messagingSenderId: '60440379548',
    projectId: 'bimaapp2025may',
    storageBucket: 'bimaapp2025may.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQk65-1cZp3SMOd1u0-OL6zFlfluUTnAY',
    appId: '1:60440379548:ios:177372424f6d77f4d62d59',
    messagingSenderId: '60440379548',
    projectId: 'bimaapp2025may',
    storageBucket: 'bimaapp2025may.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8lJ8hOd9BoD-ZR-IwTW6Byn4NoRu6cFQ',
    appId: '1:60440379548:web:8f78c1766ad95ed6d62d59',
    messagingSenderId: '60440379548',
    projectId: 'bimaapp2025may',
    authDomain: 'bimaapp2025may.firebaseapp.com',
    storageBucket: 'bimaapp2025may.firebasestorage.app',
  );

static Future<void> enableFirestorePersistence() async {
  if (!kIsWeb) {
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );
  } else {
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: false, // Disable persistence on web
    );
  }
}
}
